### PR TITLE
fix #32 quick workaround

### LINKED ISSUE #32: issue: when oldNumShards is nil
```
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)                                                                                                 
        /workspace/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105                                                                             
panic(0x1cc21a0, 0x329aed0)                                                                                                                                     
        /usr/local/go/src/runtime/panic.go:679 +0x1b2                                                                                                           
github.com/Carrefour-Group/elastic-phenix-operator/pkg/utils.(*Elasticsearch7).updateIndexSettings(0xc0018c27c0, 0x21fd5a0, 0xc0018ea9c0, 0xc000499f20, 0xf, 0xc
000812240, 0x228, 0x0, 0x18, 0x1f34d8b)                                                                                                                         
        /workspace/pkg/utils/elasticsearch7.go:214 +0x168                                                                                                       
github.com/Carrefour-Group/elastic-phenix-operator/pkg/utils.(*Elasticsearch7).CreateOrUpdateIndex(0xc0018c27c0, 0x21fd5a0, 0xc0018ea9c0, 0xc000499f20, 0xf, 0xc
000812240, 0x228, 0x0, 0x0, 0x0)                                                                                                                                
        /workspace/pkg/utils/elasticsearch7.go:164 +0x234                                                                                                       
github.com/Carrefour-Group/elastic-phenix-operator/pkg/controllers.(*ElasticIndexReconciler).Reconcile(0xc0000bb140, 0xc000499ee0, 0xe, 0xc000a96200, 0x1f, 0xc0
0038bcd8, 0xc0007ee240, 0xc00098e768, 0x21d3a40)                                                                                                                
        /workspace/pkg/controllers/elasticindex_controller.go:86 +0xb06                                                                                         
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0001be000, 0x1d12e00, 0xc00000de60, 0x43ec00) 
```

### PR DESCRIPTION
**Pull request by sjeandeaux**
We are facing nil access

### CODE REVIEW

**Review by ravetdavid — APPROVED** [review]

File: pkg/utils/elasticsearch7.go [hunk 1]
```diff
@@ -192,6 +192,14 @@ func (es *Elasticsearch7) CreateOrUpdateIndex(ctx context.Context, indexName str
...
 }
 
+// ptrToString return (nil) if the ptr is nil or the value
+func ptrToString(ptr *int32) string {
+	if ptr == nil {
+		return "(nil)"
+	}
+	return fmt.Sprintf("%d", *ptr)
+}
+
```
Comment (wmellouli) [inline pkg/utils/elasticsearch7.go]: You should move this code to `elasticsearch_common.go`, and add the same workaround to `elasticsearch8.go` too (for elasticsearch 8 client).

**Review by wmellouli — CHANGES_REQUESTED** [review]

File: pkg/utils/elasticsearch7.go (hunk 1 above)
Comment (sjeandeaux) [reply pkg/utils/elasticsearch7.go]: When looking the code, there is lot of copy/paste. In my opinion, there is not only this part to move in "common stuff".

Comment (sjeandeaux) [reply pkg/utils/elasticsearch7.go]: We should work on the naming as well. 

`isShardsUpdated` if true it is in error with we cannot update.

**Review by wmellouli — APPROVED** [review]
